---
title: "Sales Report"
author: "Davis Rakhshan"
date: "2024-07-03"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    code_folding: none
    df_print: paged
    highlight: tango
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 2
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    eval = TRUE,
    message = FALSE,
    warning = FALSE,
    out.width = "100%",
    out.height = "500px",
    fig.pos = "center",
    dpi = 300,
    fig.align = "center"
)
library(tidyverse)
library(lubridate)
library(plotly)
library(dplyr)

source("00_scripts/plot_sales.R")

# Load the data
bikes_tbl      <- readRDS("bikes_tbl.rds")
bikeshops_tbl  <- readRDS("bikeshops_tbl.rds")
orderlines_tbl <- readRDS("orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
  left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
  mutate(total_price = price_euro * quantity)

format_to_euro <- function(x, suffix = " €") {
  scales::dollar(x,
                 suffix       = suffix,
                 prefix       = "",
                 big.mark     = ".",
                 decimal.mark = ",")
}

euro_format <- function(scale        = 1,
                        prefix       = "",
                        suffix       = " €",
                        big.mark     = ".",
                        decimal.mark = ",") {
  scales::dollar_format(suffix       = suffix,
                        prefix       = prefix,
                        big.mark     = big.mark,
                        decimal.mark = decimal.mark,
                        scale        = scale)
}


# Prepare the data
total_sales_q_tbl <- bike_orderlines_tbl %>%
  select(order_date, total_price) %>%
  mutate(date_rounded = floor_date(order_date, unit = "quarter")) %>%
  group_by(date_rounded) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%
  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                Date: {date_rounded %>% format('%B %Y')}"))

# Create the plot
g1 <- total_sales_q_tbl %>%
  ggplot(aes(x = date_rounded, y = total_sales)) +
  geom_point(aes(text = label_text), color = "#2C3E50") +
  geom_smooth(method = "loess", span = 0.2) +
  scale_y_continuous(labels = euro_format()) +
  expand_limits(y = 0) +
  labs(
    title = "Total Sales",
    y = "Revenue (EUR)",
    x = ""
  )


# Prepare the data
category_2_sales_m_tbl <- bike_orderlines_tbl %>%
  select(order_date, category_1, category_2, total_price) %>%
  mutate(date_rounded = floor_date(order_date, unit = "month")) %>%
  group_by(date_rounded, category_1, category_2) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%
  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                Date: {date_rounded %>% format('%B %Y')}")) %>%
  mutate(category_2 = as_factor(category_2) %>%
           fct_reorder2(date_rounded, total_sales))

# Create the plot
g2 <- category_2_sales_m_tbl %>%
  filter(category_1 == "Road") %>%
  ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +
  geom_point(aes(text = label_text)) +
  geom_smooth(method = "loess", span = 0.2) +
  facet_wrap(~ category_2, scales = "free_y", ncol = 3) +
  expand_limits(y = 0) +
  theme(legend.position = "none",
        strip.text.x = element_text(margin = margin(5, 5, 5, 5, unit = "pt"))) +
  scale_y_continuous(labels = euro_format(scale = 1e-3, suffix = "K €")) +
  labs(
    title = "Sales By Category 2",
    y = "", x = ""
  )

```

# Total Sales Charts {.tabset .tabset-fade .tabset-pills}

## Quarterly Sales Trends

```{r, out.height="600px"}
# Render the plot
if(knitr::is_html_output()) {
  ggplotly(g1, tooltip = "text")
} else {
  g1
}
```

## Monthly Sales Trends


```{r, out.height="600px"}
plot_total_sales(bike_orderlines_tbl, unit = "month", date_format = "%B %d, %Y", interactive = FALSE)
```

## Weekly Sales Trends

```{r, out.height="600px"}
plot_total_sales(bike_orderlines_tbl, unit = "week", date_format = "%B %d, %Y", interactive = FALSE)
```


# Category Sales Charts {.tabset .tabset-fade .tabset-pills}

##  Road {.tabset .tabset-fade .tabset-pills}


### Quarterly
```{r, out.height="600px"}
plot_categories(category_1 = "Road", 
                 category_2 = "(Race|Triathlon Bike|Endurance|Cyclocross)", 
                 unit = "quarter",
                 ncol = 1, 
                 scales = "free_y", 
                 date_format = "%Y-%m-%d", 
                interactive = FALSE)
```

### Monthly
```{r, out.height="600px"}
plot_categories(category_1 = "Road", 
                 category_2 = "(Race|Triathlon Bike|Endurance|Cyclocross)", 
                 unit = "month",
                 ncol = 1, 
                 scales = "free_y", 
                 date_format = "%Y-%m-%d", 
                interactive = FALSE)
```

### Weekly
```{r, out.height="600px"}
plot_categories(category_1 = "Road", 
                 category_2 = "(Race|Triathlon Bike|Endurance|Cyclocross)", 
                 unit = "week",
                 ncol = 1, 
                 scales = "free_y", 
                 date_format = "%Y-%m-%d", 
                interactive = FALSE)
```


## Mountain {.tabset .tabset-fade .tabset-pills}

### Quarterly
```{r}
plot_categories(category_1 = "Mountain", 
                category_2 = "(Trail|Cross-Country|Enduro|Downhill|Fat Bikes|Dirt Jump)", 
                unit = "quarter",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d", 
                interactive = FALSE)
```

### Monthly
```{r}
plot_categories(category_1 = "Mountain", 
                category_2 = "(Trail|Cross-Country|Enduro|Downhill|Fat Bikes|Dirt Jump)", 
                unit = "month",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d", 
                interactive = FALSE)
```

### Weekly
```{r}
plot_categories(category_1 = "Mountain", 
                category_2 = "(Trail|Cross-Country|Enduro|Downhill|Fat Bikes|Dirt Jump)", 
                unit = "week",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d", 
                interactive = FALSE)
```


